{
 "title": "Room Lab",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NOx Level",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nox_stickoxidde",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=", "value": "room_lab" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nox_stickoxidde",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10,
         2
        ],
        "type": "holt_winters_with_fit"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=", "value": "room_lab" }
     ]
    }
   ]
  },
  {
   "title": "Carbon Monoxide",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "carbon_monoxide",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "predict" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Benzene Level",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "benzene",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=", "value": "room_lab" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Level",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "predicted_upper" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "predicted_lower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "predicted_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=", "value": "room_lab" }
     ]
    }
   ]
  }
 ]
}